name: Prune Forks on Tenderly

on:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prune forks
        run: |
          touch .env
          echo NEXT_PUBLIC_TENDERLY_SIM_API_KEY=${{ secrets.NEXT_PUBLIC_TENDERLY_SIM_API_KEY }} >> .env
          echo  =${{ secrets.NEXT_PUBLIC_TENDERLY_USER }} >> .env
          echo NEXT_PUBLIC_TENDERLY_PROJECT=${{ secrets.NEXT_PUBLIC_TENDERLY_PROJECT }} >> .env
          ./scripts/tenderly-prune.sh
